### ISSUE TITLE
Performance on the cifar dataset when the noise rate is 0.9

### ISSUE THREAD

**Issue by wangjie-123** [lxysl/PLReMix#2]
When I trained cifar10 with a noise rate of 0.9, I found that the experimental results were not ideal. However, I strictly followed the current code and settings to run the code, and at other noise rates, I can basically achieve the results of the paper.
![image](https://github.com/user-attachments/assets/f67e479a-c54f-443c-a076-7afb026af39e)

**Comment by lxysl** [comment]
I reran the experiment for cifar-10 0.9 and did not find any accuracy errors. You can try running it multiple times to eliminate instability.
